name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    
    - name: mkdir tmp
      run: mkdir tmp
    - name: Intall dotnet try
      run: dotnet tool install dotnet-try --tool-path ./tmp
    - name: Verify docs
      run: ./tmp/dotnet-try verify
